/**
 * @file primitives.h
 * @brief Shapes generated by code (circle, sphere) as plain vertex/index data.
 * @author DreGi0
 * @date October 3rd, 2026
 */

#pragma once

#include <vector>

namespace Stellar
{
    /**
     * @struct MeshData
     * @brief Vertex and index data ready to be uploaded with Mesh.
     *
     * No OpenGL here, so it can be tested without a window.
     */
    struct MeshData
    {
        std::vector<float> vertices; ///< x, y, z, r, g, b per vertex (the layout Mesh expects)
        std::vector<unsigned int> indices; ///< Which vertices make each line or triangle
    };

    /**
     * @brief A circle of radius 1 on the XY plane, meant to be drawn as GL_LINE_LOOP.
     * @param segments How many points the circle has.
     * @return One vertex and one index per point.
     */
    MeshData unitCircle(int segments);

    /**
     * @brief A UV sphere of radius 1 centered at the origin, with the poles on +Z and -Z.
     * @param stacks Rings from pole to pole (latitude).
     * @param slices Cuts around the Z axis (longitude).
     * @return (stacks + 1) * (slices + 1) white vertices and 6 indices per cell (two triangles).
     */
    MeshData unitSphere(int stacks, int slices);
} // Stellar
